/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tetris;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import tetris.engine.Board;
import tetris.engine.GameEngine;
import tetris.graphics.GameWindow;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        GameEngine gameEngine = new GameEngine();
        GameWindow gameWindow = new GameWindow(gameEngine.getBoard());

        Scene scene = new Scene(gameWindow.getRoot(), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}