/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tetris;

import javafx.application.Application;
import javafx.stage.Stage;
import tetris.controller.GameController;
import tetris.engine.GameEngine;
import tetris.engine.type.GameState;
import tetris.graphics.GameWindow;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        GameState gameState = null;
        GameEngine gameEngine = new GameEngine(gameState);
        GameWindow gameWindow = new GameWindow(gameEngine);

        GameController controller = new GameController(gameEngine, gameWindow, gameState);
        gameEngine.setSpawnListener(controller);
        controller.setSoftDropFactor(15);
        gameEngine.setGameOverListener(controller);

        
        // gameEngine.loop();
        gameWindow.execute(stage);
    }

    public static void main(String[] args) {
        launch();
    }

}